### ISSUE TITLE
certificate expired

### ISSUE THREAD

**Issue by bimimicah** [tryphotino/photino.Documentation#11]
The certificate for https://tryphotino.kavadocs.com/ seems to have expired

**Comment by MikeYeager** [comment]
Fixed! (finally!)

**Comment by bimimicah** [comment]
I've tried it in multiple browsers on different computers.... I think it's still expired.

**Comment by MikeYeager** [comment]
Documentation has been moved to https://docs.tryphotino.io/   Cheers!
