### ISSUE TITLE
Best practice guide for distributing updates

### ISSUE THREAD

**Issue by OzBob** [tryphotino/photino.Documentation#12]
How does a Photino app manage major and minor updates for the packaged files?

I stopped using "AppCenter" (https://appcenter.ms/), the Visual Studio app publishing replacement for HockeyApp because it didn't support version update events for WPF apps, and the only alternative besides 'roll your own' Windows.Squirrel (https://github.com/Squirrel/Squirrel.Windows) stopped being worked on in 2020.

This is the docs from AppCenter for Xamarin app updates distributed by the AppCenter: https://docs.microsoft.com/en-us/appcenter/sdk/distribute/xamarin

This is the docs for Squirrel.Windows when updating an installed app. Publish files to your own webapp and then Squirre.Windows will notify the user, https://github.com/Squirrel/Squirrel.Windows/blob/develop/docs/getting-started/5-updating.md

I couldn't find a photinto discord/slack/forums link, so if there is better place to put this 'feature request'/'open discussion' I'd be happy to move it there :-)

**Comment by MikeYeager** [comment]
This is not an area we've dedicated much time to. We've been relying on other technologies to handle this. There are 2 types of updates for a Photino app. Updating your content can be handled by custom code to check for new files and download them. This is something we'd like to implement in Photino at some point. The second kind of update is to update Photino itself. For this we've been relying on 3rd party installers. Any method of installing a .NET console application will work. This type of update is probably not something we'd take on ourselves. ClickOnce and VSIX should be able to deploy and update console apps via a web site (though both technologies have their issues). As far as deployment and updates through a public store, I don't believe we have much we can do about it.

**Comment by philippjbauer** [comment]
The guide for publishing on all platforms is available as a sample in the Photino.Samples repository as a separate project. It includes a publish script and packaging templates that can be adapted for your specific situation.

Currently only available in the debug branch (as of 03/19/2024), lets find the rough edges together! :)
https://github.com/tryphotino/photino.Samples/tree/debug/Photino.PublishPhotino

There's probably room for improvement regarding updating apps that should be added here as well.
