### ISSUE TITLE
Certificate expired for docs.tryphotino.io

### ISSUE THREAD

**Issue by jupjohn** [tryphotino/photino.Documentation#15]
Tried to load up the docs today and discovered that the SSL cert issued to the site expired on the 26th February. Since this is the second time an issue has been raised here about cert expiration, I would recommend setting up a scheduled reminder to renew it.

**Comment by MikeYeager** [comment]
@jammehcow Thank you for the heads up. I will inform our IT people.

**Comment by LauraWebdev** [comment]
This has been fixed at some point, next expiration date is September 4th.
