### ISSUE TITLE
Questions for participation

### ISSUE THREAD

**Issue by LauraWebdev** [tryphotino/photino.Documentation#16]
Hey everyone,

I've extensively used photino(.NET) in my recent project for over a month now and noticed how often I went to the git repository / straight into the source code instead of the documentation page. I think it needs better API documentation and generally more ressources to get started.

I'd be committed to contribute to this (specifically the photino.NET area of the project) but wanted to ask first what scope and purpose the documentation pages have. I want to understand if the current state of the docs is deliberate or just due to insufficient ressources.

**Comment by philippjbauer** [comment]
Hi Laura,

thank you very much for offering your help with the documentation! It's been more of a resource issue than anything else. We are thinking that the documentation can need the update and that a separate wiki is a good idea for guides and show-and-tell type of articles.

What are your thoughts on how to improve the documentation? How would it be more useful to you? You're most welcome to send PRs with your improvements and we'll review them.

**Comment by LauraWebdev** [comment]
I think the hardest part getting into Photino was understanding the API. Things like the recent native dialogs are not really documented, if so, it's only on the "Whats New" page or via a single bullet point in a list. Most recently, I've had to digg into the source code implementation to understand the `ShowOpenFolder` and `ShowOpenFile` functions.

I'd love to expand the documentation and provide small usage samples for APIs, concepts etc. Maybe there is a way to generate API docs from the sourcecode, I'd love checking that out. Maybe some guides to get started and getting familiar with Photino's concepts and potential constrains. I've noticed after a week of looking around and playing around, it's probably my favorite way of development for desktop applications.

**Comment by philippjbauer** [comment]
We think it's a great idea to have some usage examples. We should probably focus on the harder to grok parts of the API, i. e. settings and methods that aren't just true/false flags. Go ahead and give it a go! We certainly appreciate your involvement in the project and the high praise! :)

**Comment by LauraWebdev** [comment]
Awesome, I'm guessing standard markdown will do?

**Comment by philippjbauer** [comment]
Absolutely!

**Comment by LauraWebdev** [comment]
Awesome, I'll close this issue then, as all my questions were answered 😄
