### ISSUE TITLE
Is there API Documentation?

### ISSUE THREAD

**Issue by crm76** [tryphotino/photino.Documentation#19]
Am I crazy or is there not any documentation that lists and describes the methods and properties?

**Comment by MikeYeager** [comment]
@crm76 You are not crazy. The code is annotated to show up in IntelliSense. One could generate docs from this using 3rd party tools, but we have not. We also do include all potential calls in the TestBench sample and update that as new calls are added. If you or someone else from the community would like to generate these docs and add them, we'd be happy for the help.

**Comment by MikeYeager** [comment]
Closed due to inactivity.
